summary: Debian releases
summary.alt.lang.id_ID: Rilis Debian
fields:
  codename: {schema: 'str*', pos: 0, summary: "Name (in Indonesian)", sortable: Yes, unique: Yes}
  version: {schema: 'str*', pos: 1, summary: "Name (in Indonesian)", sortable: Yes, unique: Yes}
  #latest_point_version: {schema: 'str*', pos: 2, summary: "", sortable: Yes, unique: Yes}
  #latest_date: {schema: 'date*', pos: 3summary: "", sortable: Yes}
  #is_released: {schema: 'bool*', pos: 0, summary: "Name (in Indonesian)", sortable: Yes}
pk: codename
